### ISSUE TITLE
Use problem

### ISSUE THREAD

**Issue by LudovicFauchet** [Mte90/Wordmove-Tools#1]
Hello,

I can not use the script, i had to do a bad thing in the installation...

I tried to do `wordmove-path-detect staging`

An the terminal answer is
`-bash: /usr/local/bin/wordmove-path-detect: /usr/bin/php: bad interpreter: No such file or directory`

Thanks for your help

**Comment by Mte90** [comment]
the scripts require php-cli on your system to work :-)

**Comment by LudovicFauchet** [comment]
Hello,  

I'am Mac user so I have php-cli installed by default !?

Best regards  

## 

Ludovi Fauchet - Pro
Envoyé avec Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Mte90** [comment]
i don't know i using Linux

**Comment by LudovicFauchet** [comment]
Ok so, i checked it, i have php-cli installed and yaml too, so what i have to do to use these scripts ?  

## 

Ludovi Fauchet - Pro
Envoyé avec Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Mte90** [comment]
i don't know for OSX, the path for php cli on linux is /usr/bin/php you need to change with your path.

**Comment by LudovicFauchet** [comment]
I resolved my problem, a xcode library was missing... I uninstall libyaml and install it again...

It works lika a charm ;)

Thanks
